spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: postgres
    password: postgres
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuerUri: https://cognito-idp.eu-north-1.amazonaws.com/eu-north-1_tHdQ1zGu8
  flyway:
    enabled: false

aws:
  accessKey: ${AWS_ACCESS_KEY:}
  secretAccessKey: ${AWS_SECRET_ACCESS_KEY:}
  cognito:
    userPoolId: ${COGNITO_USER_POOL_ID:}
    clientId: ${COGNITO_CLIENT_ID:}
    clientSecret: ${COGNITO_CLIENT_SECRET:}
    region: ${COGNITO_REGION:}

