package com.swiftpay.swiftpay_scheduler.service.validation;

public enum ValidatorType {
    CREATE_USER_VALIDATOR,
    CREATE_TRANSFER_VALIDATOR,
    TRANSFER_BALANCE_VALIDATOR,
    TRANSFER_CANCELLATION_VALIDATOR,
    TRANSFER_DATE_VALIDATOR,
    TRANSFER_DELETION_SERVICE,
    UPDATE_TRANSFER_VALIDATOR,
    DEPOSIT_BALANCE_VALIDATOR,
}
